#!/bin/bash
# Quick command reference for starting the application

echo "╔════════════════════════════════════════════════════════════╗"
echo "║        SemanticSearch Application - Quick Start            ║"
echo "╔════════════════════════════════════════════════════════════╗"
echo ""
echo "Open 3 separate terminals and run these commands:"
echo ""
echo "┌─ Terminal 1: Recommender Service ──────────────────────────┐"
echo "│                                                             │"
echo "│  cd src/recommender                                         │"
echo "│  python3 api.py                                             │"
echo "│                                                             │"
echo "│  Keep this running. Should see:                            │"
echo "│  'Uvicorn running on http://0.0.0.0:8000'                  │"
echo "└─────────────────────────────────────────────────────────────┘"
echo ""
echo "┌─ Terminal 2: Aspire Application ───────────────────────────┐"
echo "│                                                             │"
echo "│  cd src/SemanticSearch.AppHost                              │"
echo "│  dotnet run                                                 │"
echo "│                                                             │"
echo "│  This starts all .NET services + infrastructure            │"
echo "└─────────────────────────────────────────────────────────────┘"
echo ""
echo "┌─ Terminal 3: Frontend (Optional) ──────────────────────────┐"
echo "│                                                             │"
echo "│  cd src/semantic-search-frontned                            │"
echo "│  npm run dev                                                │"
echo "│                                                             │"
echo "│  Open: http://localhost:5173                               │"
echo "└─────────────────────────────────────────────────────────────┘"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "Testing:"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "Test recommender is running:"
echo "  curl http://localhost:8000/"
echo ""
echo "Test categories endpoint:"
echo "  curl http://localhost:XXXX/api/categories"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "Troubleshooting:"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "If recommender crashes with segfault:"
echo "  1. Use virtual environment: python3 -m venv venv && source venv/bin/activate"
echo "  2. Try: pip3 install tensorflow-macos (Apple Silicon)"
echo "  3. See: MANUAL_RECOMMENDER_SETUP.md"
echo ""
echo "If port 8000 is busy:"
echo "  lsof -i :8000"
echo ""
