syntax = "proto3";

option csharp_namespace = "Mneme.Api";

package product;

service ProductSearch {
  // Search for products using vector similarity
  rpc SearchProducts (ProductSearchRequest) returns (ProductSearchResponse);

  // Batch upsert products into the database
  rpc UpsertProducts (UpsertProductsRequest) returns (UpsertProductsResponse);
}

message ProductSearchRequest {
  repeated float textVector = 1;
  repeated float imageVector = 2;
  int32 limit = 3;
}

message ProductSearchResponse {
  repeated Product products = 1;
}

message UpsertProductsRequest {
  repeated Product products = 1;
}

message UpsertProductsResponse {
  int32 count = 1;
  bool success = 2;
  string message = 3;
}

message Product {
  string id = 1;
  string name = 2;
  string description = 3;
  float score = 4; // Output only

  repeated float textVector = 5; // Input only
  repeated float imageVector = 6; // New: Image Embeddings

  // Flexible key-value pairs for things like "color", "category", "url"
  map<string, string> metadata = 7;
}