<Project Sdk="Microsoft.NET.Sdk.Worker">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>dotnet-DatabaseSeeder-d57be7a9-2e97-4c57-9926-e7d804780fcb</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Aspire.Npgsql" Version="10.0.0"/>
        <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.0"/>
    </ItemGroup>

    <ItemGroup>
        <None Update="Data\*.csv">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>
</Project>
